tools:
  # 是否开启请求接口
  asyncio_http_tf: True
  # 小程序结果保存的文件名
  proess_file: "proess.xlsx"
  # 不进行拼接的接口的url,不写入该状态码的接口
  not_asyncio_http: ["weixin.qq.com", "www.w3.org", "map.qq.com", "restapi.amap.com"]
  not_asyncio_stats: [404]
  # 最大线程数
  max_workers: 5

wx-tools:
  wx-file: 'D:\tools\WeChat-tool\WeChat Files'

bot:
  # 飞书机器人配置，是否开启飞书提醒
  feishu-tf: False
  api_id: ""
  api_secret: ""
  phone: [""]

